### ISSUE TITLE
Virtualbox vm doesn't work on intel cpu

### ISSUE THREAD

**Issue by phpsystems** [ashemery/CuckooVM#1]
Getting an error message saying:

X86_CPUID_AMD_FEATURE_EDX_AXM_MX is not supported by the host but has already been exposed to the guest [ver=17 pass=final] (VERR_SSM_LOAD_CPUID_MISMATCH)

**Comment by ashemery** [comment]
I'll need to go to the office and get my hands on an Intel machine to check this out. Thank you for letting me know.

**Comment by ashemery** [comment]
I've fixed the issue, it's because of the Windows VM was created using AMD, so I just created another Windows VM and it is working like a charm. Need to compress and upload it, which will be coming very soon.

If you do not want to wait, just install another Windows VM and change the cuckoo virtualbox.conf settings to point to it and you're good to go.

Thanks again for reporting this.

**Comment by ashemery** [comment]
Here is the solution: https://archive.org/download/CuckooVM/Win7_Intel.tar

I'm closing this issue and thanks again.
