### ISSUE TITLE
No ability to analyse Excel or word files

### ISSUE THREAD

**Issue by phoenixml** [ashemery/CuckooVM#4]
Hi All,

It's looks like no ability to analyse word or Excel files just wondering if this is was not considered while creating win7 box as per cuckoo documentation there was a set of commands to include these tools any clarification would be appreciated, Also I noticed that's once I am analysing a url the explorer web browsing dosent open but a CMD console instead establish http connection from my understanding that this might affect some malwares behaviours because some will be waiting for a specific web agent to perform the next action.

Can you please advise if i have to create a new machines and choose the missing tools and applications like excel word , pdf etc ...
Or edit the current machine and recreate a new snapahot.
Or the tools and applications already there?

thank you :)

**Comment by ashemery** [comment]
Hi Tarek,

It was, but the problem is with the license of word and excel. I don't know how that works and didn't want to get into such issues. I think the PDF is easier to solve, but word|excel are not.

Now, if I understood you correctly; are you asking me to create another Windows VM to solve the URL/PDF/Word thing? :)

Thank you for all your feedback, I will see when we can start working again on this project.

**Comment by phoenixml** [comment]
Hi Dr no I didn't mean you recreate a new machine 😁, I will do so I have word and excel license so I will be doing That and build more And multiple sandboxies machines , I just opened this issue just for refernce😬 and proividing feedback I like this project and I will be adding more feedbacks while I am working on it 👍🏻
